// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'beaver-item-info-row-example-label'
  | 'beaver-item-pane-status'
  | 'beaver-item-section-example1-head-text'
  | 'beaver-item-section-example1-sidenav-tooltip'
  | 'beaver-item-section-example2-button-tooltip'
  | 'beaver-item-section-example2-head-text'
  | 'beaver-item-section-example2-sidenav-tooltip'
  | 'beaver-menu-upsert'
  | 'beaver-menuitem-filemenulabel'
  | 'beaver-menuitem-label'
  | 'beaver-menuitem-submenulabel'
  | 'beaver-menupopup-label'
  | 'beaver-pref-enable'
  | 'beaver-pref-help'
  | 'beaver-pref-input'
  | 'beaver-pref-section-account-heading'
  | 'beaver-pref-section-account-text'
  | 'beaver-pref-section-keys-anthropic'
  | 'beaver-pref-section-keys-google'
  | 'beaver-pref-section-keys-heading'
  | 'beaver-pref-section-keys-openai'
  | 'beaver-pref-section-keys-text'
  | 'beaver-prefs-table-detail'
  | 'beaver-prefs-table-title'
  | 'beaver-prefs-title'
  | 'beaver-startup-begin'
  | 'beaver-startup-finish'
  | 'beaver-tabpanel-lib-tab-label'
  | 'beaver-tabpanel-reader-tab-label';
