// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "userId": string;
      "userEmail": string;
      "currentPlanId": string;
      "installedVersion": string;
      "showIndexingCompleteMessage": boolean;
      "showHighTokenUsageWarningMessage": boolean;
      "authMethod": string;
      "keyboardShortcut": string;
      "statefulChat": boolean;
      "addSelectedItemsOnOpen": boolean;
      "addSelectedItemsOnNewThread": boolean;
      "annotationToolEnabled": boolean;
      "maxAddAttachmentToMessage": number;
      "maxFileSizeMB": number;
      "maxPageCount": number;
      "autoApplyAnnotations": boolean;
      "autoImportItems": boolean;
      "deferredToolPreferences": string;
      "customInstructions": string;
      "googleGenerativeAiApiKey": string;
      "openAiApiKey": string;
      "anthropicApiKey": string;
      "lastUsedModel": string;
      "customChatModels": string;
      "recentItems": string;
      "citationFormat": string;
      "citationStyle": string;
      "citationLocale": string;
      "customPrompts": string;
      "deletionJobs": string;
      "skippedItems": string;
      "runConsistencyCheck": boolean;
      "runCollectionSync": boolean;
      "runWebDAVSync": boolean;
      "runEmbeddingFullDiff": boolean;
      "pendingVersionNotifications": string;
    };
  }
}
