// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "userId": string;
      "userEmail": string;
      "currentPlanId": string;
      "installedVersion": string;
      "showIndexingCompleteMessage": boolean;
      "showHighTokenUsageWarningMessage": boolean;
      "authMethod": string;
      "keyboardShortcut": string;
      "statefulChat": boolean;
      "addSelectedItemsOnOpen": boolean;
      "addSelectedItemsOnNewThread": boolean;
      "addBeaverProvenanceNote": boolean;
      "focusResponseForScreenReaders": boolean;
      "annotationToolEnabled": boolean;
      "annotationAuthorName": string;
      "maxAddAttachmentToMessage": number;
      "readerExplainPrompt": string;
      "imeCompositionOrderFix": boolean;
      "debugImeTrace": boolean;
      "accessRemoteFiles": boolean;
      "dataProviderEnabled": boolean;
      "autoApplyAnnotations": boolean;
      "autoCreateNotes": boolean;
      "autoImportItems": boolean;
      "confirmExtractionCosts": boolean;
      "confirmExternalSearchCosts": boolean;
      "confirmCredits": boolean;
      "creditConfirmThreshold": number;
      "requestPlusTools": boolean;
      "showDiffPreviewInNoteEditor": boolean;
      "enableSystemNotifications": boolean;
      "enableResponseCompleteNotifications": boolean;
      "deferredToolPreferences": string;
      "customInstructions": string;
      "googleGenerativeAiApiKey": string;
      "openAiApiKey": string;
      "anthropicApiKey": string;
      "lastUsedModel": string;
      "customChatModels": string;
      "recentItems": string;
      "citationFormat": string;
      "citationStyle": string;
      "citationLocale": string;
      "useTemporaryCitationAnnotations": boolean;
      "usePageLabels": boolean;
      "customPrompts": string;
      "customPromptsLastUsed": string;
      "actions": string;
      "actionsLastUsed": string;
      "legacyPromptsImported": boolean;
      "deletionJobs": string;
      "skippedItems": string;
      "onboardingWelcomeShown": boolean;
      "onboardingReaderTipShown": boolean;
      "onboardingReaderTipShownV2": boolean;
      "onboardingNoteTipShown": boolean;
      "onboardingCitationTipShown": boolean;
      "onboardingWelcomeShownAt": string;
      "versionUpdatePopupShownAt": string;
      "onboardingSignInTextShown": boolean;
      "interruptedThread": string;
      "threadsClaimKey": string;
      "mcpServerEnabled": boolean;
      "mcpCreateNoteToolEnabled": boolean;
      "backgroundExtractorEnabled": boolean;
      "runConsistencyCheck": boolean;
      "runCollectionSync": boolean;
      "runWebDAVSync": boolean;
      "runEmbeddingFullDiff": boolean;
      "pendingVersionNotifications": string;
      "librarySuggestions": string;
      "librarySuggestionsGeneratedAt": string;
      "firstRunAssignments": string;
      "maxAttachmentFileSizeMB": number;
      "tables.defaultLibraryID": number;
      "tables.openIn": string;
      "tables.interceptDoubleClick": boolean;
    };
  }
}
