// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "userId": string;
      "userEmail": string;
      "currentPlanId": string;
      "installedVersion": string;
      "showIndexingCompleteMessage": boolean;
      "showHighTokenUsageWarningMessage": boolean;
      "authMethod": string;
      "keyboardShortcut": string;
      "statefulChat": boolean;
      "addSelectedItemsOnOpen": boolean;
      "addSelectedItemsOnNewThread": boolean;
      "annotationToolEnabled": boolean;
      "maxAddAttachmentToMessage": number;
      "readerExplainPrompt": string;
      "maxFileSizeMB": number;
      "maxPageCount": number;
      "autoApplyAnnotations": boolean;
      "autoCreateNotes": boolean;
      "autoImportItems": boolean;
      "confirmExtractionCosts": boolean;
      "confirmExternalSearchCosts": boolean;
      "pauseLongRunningAgent": boolean;
      "requestPlusTools": boolean;
      "deferredToolPreferences": string;
      "customInstructions": string;
      "googleGenerativeAiApiKey": string;
      "openAiApiKey": string;
      "anthropicApiKey": string;
      "lastUsedModel": string;
      "customChatModels": string;
      "recentItems": string;
      "citationFormat": string;
      "citationStyle": string;
      "citationLocale": string;
      "customPrompts": string;
      "customPromptsLastUsed": string;
      "actions": string;
      "actionsLastUsed": string;
      "legacyPromptsImported": boolean;
      "deletionJobs": string;
      "skippedItems": string;
      "onboardingWelcomeShown": boolean;
      "onboardingReaderTipShown": boolean;
      "onboardingCitationTipShown": boolean;
      "onboardingWelcomeShownAt": string;
      "mcpServerEnabled": boolean;
      "runConsistencyCheck": boolean;
      "runCollectionSync": boolean;
      "runWebDAVSync": boolean;
      "runEmbeddingFullDiff": boolean;
      "pendingVersionNotifications": string;
    };
  }
}
