/**
 * Reference classifier runtime.
 *
 * Stage 1 is a logistic regression over each item's own and context
 * features. Stage 2 is a small gradient-boosted tree ensemble over the
 * stage-1 logits of the item and its two neighbours on each side (reading
 * order across page breaks), page-level aggregates of the stage-1
 * probabilities, and the stage-1 features again. All three models (with the
 * line model of `lines.ts`) are binary models of the shared runtime
 * (`../models/runtime.ts`). Weights are generated by the research pipeline
 * into `weights.ts`; `stage2Features` mirrors its Python twin exactly.
 */

import {
    binaryProbability,
    binaryScore,
    sigmoid,
    type LogisticModel,
    type ModelInfo,
    type TreeModel,
} from "../models/runtime";
import { CONTEXT_FEATURES, ITEM_FEATURES, contextFeatures, itemFeatures } from "./features";
import type { InputPage } from "../features/itemInput";

export interface ReferenceModel {
    /** Provenance, for humans. */
    trainedOn: string;
    /** Stage 1 over `ITEM_FEATURES` then `CONTEXT_FEATURES` (`FEATURE_VERSION`). */
    stage1: LogisticModel & Pick<ModelInfo, "featureVersion">;
    /** Stage 2 over `STAGE2_FEATURES` then the stage-1 features. */
    stage2: TreeModel;
    /** Probability at or above which an item is a reference. */
    threshold: number;
    /** Entry-start model over the lines of reference items (see `lines.ts`). */
    lines: {
        model: TreeModel & Pick<ModelInfo, "featureVersion">;
        /** A later line at or above this start probability opens a new entry. */
        splitThreshold: number;
        /** A first line below this start probability continues the previous item. */
        mergeThreshold: number;
    };
}

const LOGIT_CLAMP = 8;
const clampLogit = (z: number) => Math.min(LOGIT_CLAMP, Math.max(-LOGIT_CLAMP, z)) / LOGIT_CLAMP;

/** Features are rounded to 4 decimals, as in the training export. */
export const roundFeature = (v: number) => Math.round(v * 1e4) / 1e4;

/** Stage-1 feature rows for a document, flattened in page and reading order. */
export function stage1Features(pages: readonly InputPage[], pageCount: number): number[][] {
    const context = contextFeatures(pages, pageCount);
    const rows: number[][] = [];
    pages.forEach((page, p) => {
        page.items.forEach((item, i) => {
            const row = itemFeatures(item, page);
            for (const v of context[p][i]) row.push(v);
            for (let j = 0; j < row.length; j++) row[j] = roundFeature(row[j]);
            rows.push(row);
        });
    });
    return rows;
}

export const STAGE1_FEATURES: readonly string[] = [...ITEM_FEATURES, ...CONTEXT_FEATURES];
const REF_HEADING = STAGE1_FEATURES.indexOf("refHeading");
const REF_HEADING_PAGE = STAGE1_FEATURES.indexOf("refHeadingPage");
const HEADINGS_AFTER = STAGE1_FEATURES.indexOf("headingsAfter");

export const STAGE2_FEATURES = [
    "self",
    "prev1",
    "prev2",
    "next1",
    "next2",
    "pageMean",
    "pageShare",
    "refHeading",
    "refHeadingPage",
    "headingsAfter",
] as const;

/**
 * Stage-2 rows: neighbour logits and page aggregates followed by the stage-1
 * features. `pageOf[i]` is the page position of row i.
 */
export function stage2Features(
    z: readonly number[],
    pageOf: readonly number[],
    stage1: readonly number[][],
): number[][] {
    const n = z.length;
    const zc = z.map(clampLogit);
    const sum = new Map<number, { p: number; share: number; n: number }>();
    for (let i = 0; i < n; i++) {
        const agg = sum.get(pageOf[i]) ?? { p: 0, share: 0, n: 0 };
        const p = sigmoid(z[i]);
        agg.p += p;
        agg.share += p >= 0.5 ? 1 : 0;
        agg.n++;
        sum.set(pageOf[i], agg);
    }
    const rows: number[][] = [];
    for (let i = 0; i < n; i++) {
        const agg = sum.get(pageOf[i])!;
        const x = stage1[i];
        const row = [
            zc[i],
            i >= 1 ? zc[i - 1] : -1,
            i >= 2 ? zc[i - 2] : -1,
            i + 1 < n ? zc[i + 1] : -1,
            i + 2 < n ? zc[i + 2] : -1,
            agg.p / agg.n,
            agg.share / agg.n,
            x[REF_HEADING],
            x[REF_HEADING_PAGE],
            x[HEADINGS_AFTER],
        ];
        for (let j = 0; j < x.length; j++) row.push(x[j]);
        rows.push(row);
    }
    return rows;
}

/** Stage-1 logit of one feature row. */
export function stage1Logit(model: ReferenceModel, x: readonly number[]): number {
    return binaryScore(model.stage1, x);
}

/** Entry-start probability of one line-feature row. */
export function lineStartProbability(model: ReferenceModel, x: readonly number[]): number {
    return binaryProbability(model.lines.model, x);
}

/** Stage-2 logit of one stage-2 row. */
export function stage2Logit(model: ReferenceModel, x: readonly number[]): number {
    return binaryScore(model.stage2, x);
}

/**
 * Reference probability of every item of a document, per page. `pages` are
 * the document's pages in order.
 */
export function scoreReferences(
    model: ReferenceModel,
    pages: readonly InputPage[],
    pageCount: number,
): number[][] {
    const x1 = stage1Features(pages, pageCount);
    const z1 = x1.map((x) => stage1Logit(model, x));
    const pageOf: number[] = [];
    pages.forEach((page, p) => page.items.forEach(() => pageOf.push(p)));
    const x2 = stage2Features(z1, pageOf, x1);
    const out: number[][] = [];
    let k = 0;
    for (const page of pages) {
        out.push(page.items.map(() => sigmoid(stage2Logit(model, x2[k++]))));
    }
    return out;
}
