import { describe, expect, it } from "vitest";

import * as pdf from "../../../src/beaver-extract";
import type {
    BoundingBox,
    CaptionItem,
    CoordOrigin,
    DegradationNote,
    DegradationReason,
    DegradationSummary,
    DocItem,
    DocItemBase,
    FootnoteItem,
    FormulaItem,
    ItemLine,
    ListItemItem,
    MarginItem,
    PageSentenceFeasibilityReport,
    PageSentenceOptions,
    PageSentenceResult,
    PictureItem,
    ReaderFrameContext,
    SectionHeaderItem,
    SentenceItem,
    SentenceTrace,
    SentenceTraceResult,
    TableItem,
    TextBearingItem,
    TextItem,
    WorkerSentenceDebugOptions,
} from "../../../src/beaver-extract";

type PublicTypeSmoke = [
    BoundingBox,
    CoordOrigin,
    DocItem,
    DocItemBase,
    TextBearingItem,
    TextItem,
    SectionHeaderItem,
    FootnoteItem,
    CaptionItem,
    ListItemItem,
    MarginItem,
    FormulaItem,
    TableItem,
    PictureItem,
    ItemLine,
    SentenceItem,
    ReaderFrameContext,
    PageSentenceResult,
    PageSentenceOptions,
    PageSentenceFeasibilityReport,
    DegradationSummary,
    DegradationNote,
    DegradationReason,
    SentenceTrace,
    SentenceTraceResult,
    WorkerSentenceDebugOptions,
];

describe("pdf barrel exports", () => {
    it("exposes the intended runtime API surface", () => {
        const expected = [
            "BeaverExtractor",
            "DEFAULT_EXTRACTION_SETTINGS",
            "DEFAULT_MARGINS",
            "DEFAULT_MARGIN_ZONE",
            "DEFAULT_OCR_DETECTION_OPTIONS",
            "DEFAULT_PAGE_IMAGE_OPTIONS",
            "DEFAULT_PDF_SEARCH_OPTIONS",
            "DEFAULT_SEARCH_ROLE_WEIGHTS",
            "DEFAULT_SEARCH_SCORING_OPTIONS",
            "DocumentAnalyzer",
            "ExtractionError",
            "ExtractionErrorCode",
            "MarginFilter",
            "MuPDFWorkerClient",
            "PageExtractor",
            "SearchScorer",
            "StyleAnalyzer",
            "bboxFromXYWH",
            "bboxHeight",
            "bboxToReaderFrame",
            "bboxToTuple",
            "bboxWidth",
            "bridgeDetailedPageFonts",
            "buildByteOffsetTable",
            "buildDetailedLineLookup",
            "buildPageAnalysisContext",
            "buildPageSentenceFeasibilityReport",
            "buildParagraphText",
            "byteRangesToCharRanges",
            "configurePDF",
            "detectColumns",
            "detectFigureTextColumns",
            "detectFilteredParagraphs",
            "detectLinesInColumn",
            "detectLinesOnPage",
            "detectParagraphs",
            "disposeMuPDFWorker",
            "extractPageSentences",
            "flipOrigin",
            "getEffectiveRepeatThreshold",
            "getMuPDFWorkerClient",
            "isConfigured",
            "logColumnDetection",
            "logLineDetection",
            "logParagraphDetection",
            "mergeBoxes",
            "normalizeLanguageCode",
            "pagesForFilterWithBridgedFonts",
            "prewarmMuPDFWorker",
            "quadsToReaderFrame",
            "resolveAnalysisPages",
            "shouldProbeGraphicsLayer",
            "simpleRegexSentenceSplit",
            "styleToKey",
        ];
        expect(Object.keys(pdf).sort()).toEqual(expected);
    });

    it("does not re-export removed schema helpers at runtime", () => {
        for (const removed of [
            "lineBBoxToRect",
            "extractSentenceBBoxes",
            "extractPageSentenceBBoxes",
            "buildFeasibilityReport",
            "flattenPageText",
            "sentenceToBoxes",
        ]) {
            expect(pdf).not.toHaveProperty(removed);
        }

        const typeSmoke: PublicTypeSmoke | null = null;
        expect(typeSmoke).toBeNull();
    });
});
