/**
 * Dev-only HTTP handler for the `/beaver/test/create-report` endpoint.
 *
 * Generates an HTML report and stores it as a Zotero snapshot attachment. Accepts
 * either an explicit report spec or a list of item keys, in which case a report is
 * synthesized from those items' real metadata and annotation counts. Wired to its
 * path in `useHttpEndpoints.ts`.
 */

import {
    createReportSnapshot,
    ReportCreationError,
    type ReportSpec,
} from '../../../src/services/reports';
import { getZoteroSelectURI } from '../../../src/utils/zoteroUtils';
import { logger } from '../../../src/utils/logger';

interface CreateReportRequest {
    spec?: ReportSpec;
    /** Build a demo report from these item keys instead of passing a spec. */
    fromItemKeys?: string[];
    libraryID?: number;
    collectionKey?: string | null;
    parentItemKey?: string | null;
    title?: string;
    tags?: string[];
    /** Open the created report in the reader. */
    open?: boolean;
}

/** Extracts a 4-digit year from a Zotero date field. */
function getYear(item: Zotero.Item): string | null {
    const raw = item.getField('date', true) as string;
    if (!raw) return null;
    const match = /\d{4}/.exec(raw);
    return match ? match[0] : null;
}

async function countAnnotations(item: Zotero.Item): Promise<number> {
    let total = 0;
    const attachmentIDs = item.getAttachments();
    if (!attachmentIDs.length) return 0;
    const attachments = await Zotero.Items.getAsync(attachmentIDs);
    for (const attachment of attachments) {
        try {
            total += attachment.getAnnotations().length;
        } catch (e) {
            // Attachment types without an annotation store are simply skipped.
        }
    }
    return total;
}

/** Picks the attachment a reader link should open, preferring PDF/EPUB/snapshot. */
async function bestReadableAttachment(item: Zotero.Item): Promise<Zotero.Item | null> {
    const attachmentIDs = item.getAttachments();
    if (!attachmentIDs.length) return null;
    const attachments = await Zotero.Items.getAsync(attachmentIDs);
    const ranked = ['application/pdf', 'application/epub+zip', 'text/html'];
    for (const contentType of ranked) {
        const hit = attachments.find((a) => a.attachmentContentType === contentType);
        if (hit) return hit;
    }
    return null;
}

function openUriFor(libraryID: number, key: string): string | null {
    const library = Zotero.Libraries.get(libraryID);
    if (!library) return null;
    // @ts-ignore groupID is defined for group libraries
    const segment = library.libraryType === 'group' ? `groups/${library.groupID}` : 'library';
    return `zotero://open/${segment}/items/${key}`;
}

/**
 * Synthesizes a report from real library items: a metadata table, an annotation-count
 * chart, and a citation list whose links resolve back into Zotero.
 */
async function buildSpecFromItems(
    libraryID: number,
    itemKeys: string[],
    title: string
): Promise<ReportSpec> {
    const items: Zotero.Item[] = [];
    for (const key of itemKeys) {
        const item = await Zotero.Items.getByLibraryAndKeyAsync(libraryID, key);
        if (item) items.push(item as Zotero.Item);
    }
    if (!items.length) {
        throw new ReportCreationError('None of the requested item keys resolved.', 'items_not_found');
    }
    await Zotero.Items.loadDataTypes(items, ['itemData', 'creators', 'childItems']);

    const rows: string[][] = [];
    const series: { label: string; value: number }[] = [];
    const citations = [];

    for (const item of items) {
        const itemTitle = (item.getField('title') as string) || '(untitled)';
        const creator = (item.getField('firstCreator') as string) || '—';
        const year = getYear(item) || '—';
        const annotations = await countAnnotations(item);

        rows.push([
            itemTitle.length > 70 ? `${itemTitle.slice(0, 69)}…` : itemTitle,
            creator,
            year,
            Zotero.ItemTypes.getLocalizedString(item.itemTypeID),
        ]);

        const shortLabel = creator.split(/\s+/)[0] || itemTitle.slice(0, 18);
        series.push({ label: `${shortLabel} ${year}`, value: annotations });

        const attachment = await bestReadableAttachment(item);
        citations.push({
            label: `${creator} (${year})`,
            reference: itemTitle,
            selectUri: getZoteroSelectURI(libraryID, item.key),
            openUri: attachment ? openUriFor(libraryID, attachment.key) : null,
        });
    }

    const withAnnotations = series.filter((s) => s.value > 0).length;

    return {
        title,
        subtitle: `${items.length} item${items.length === 1 ? '' : 's'} from your library`,
        provenance: 'Generated by Beaver — every link below resolves back into Zotero.',
        sections: [
            {
                heading: 'Summary',
                blocks: [
                    {
                        type: 'paragraph',
                        text:
                            `This report covers ${items.length} item${items.length === 1 ? '' : 's'}, ` +
                            `${withAnnotations} of which have annotations. It was produced as a Zotero ` +
                            `snapshot attachment, so it is stored, indexed, and annotatable like any other document.`,
                    },
                    {
                        type: 'callout',
                        variant: 'note',
                        title: 'Rendered without JavaScript',
                        text:
                            'The chart below is inline SVG with geometry computed at generation time, ' +
                            'because the snapshot reader blocks author scripts.',
                    },
                ],
            },
            {
                heading: 'Annotations per item',
                blocks: [
                    {
                        type: 'bar_chart',
                        series,
                        unit: 'annotations',
                        caption: 'Annotation counts across the cited items.',
                    },
                ],
            },
            {
                heading: 'Items',
                blocks: [
                    {
                        type: 'table',
                        columns: ['Title', 'Creator', 'Year', 'Type'],
                        rows,
                    },
                ],
            },
            {
                heading: 'Sources',
                blocks: [{ type: 'citations', entries: citations }],
            },
        ],
        footerNote: 'Generated by Beaver. Verify claims against the linked sources.',
    };
}

export async function handleTestCreateReportHttpRequest(request: CreateReportRequest) {
    const libraryID = request.libraryID ?? Zotero.Libraries.userLibraryID;

    try {
        let spec = request.spec;
        if (!spec) {
            if (!request.fromItemKeys?.length) {
                return { error: 'Provide either `spec` or `fromItemKeys`.' };
            }
            spec = await buildSpecFromItems(
                libraryID,
                request.fromItemKeys,
                request.title || 'Beaver library report'
            );
        }

        let collectionID: number | null = null;
        if (request.collectionKey) {
            const collection = Zotero.Collections.getByLibraryAndKey(libraryID, request.collectionKey);
            if (!collection) {
                return { error: `Collection ${request.collectionKey} not found.` };
            }
            collectionID = (collection as Zotero.Collection).id;
        }

        let parentItemID: number | null = null;
        if (request.parentItemKey) {
            const parent = await Zotero.Items.getByLibraryAndKeyAsync(libraryID, request.parentItemKey);
            if (!parent) {
                return { error: `Parent item ${request.parentItemKey} not found.` };
            }
            parentItemID = (parent as Zotero.Item).id;
        }

        const created = await createReportSnapshot({
            spec,
            libraryID,
            collectionID,
            parentItemID,
            title: request.title,
            tags: request.tags,
        });

        let opened = false;
        if (request.open) {
            await Zotero.Reader.open(created.itemID);
            opened = true;
        }

        return { ok: true, opened, report: created };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        const code = error instanceof ReportCreationError ? error.code : 'error';
        logger(`handleTestCreateReportHttpRequest: ${message}`, 1);
        return { error: message, code };
    }
}
