/**
 * Item-boundary model runtime: for a line of a page's flow, the probability
 * that it starts a new item.
 *
 * The model is a binary gradient-boosted tree ensemble of the shared runtime
 * (`../models/runtime.ts`, class 1 = start). It reads a subset of the
 * boundary features (`features.ts`), listed by name in the export: the
 * heuristic group (the paragraph detector's own decision) is left out, so
 * the runtime never runs `startNewItem` first. Weights are generated by
 * beaver-extract-models (`bxm boundaries export`) into `weights.ts`.
 */

import { binaryProbability, PACKED_TREES_FORMAT, type ModelInfo, type PackedTreeModel } from "../models/runtime";
import { FEATURES, FEATURE_SET, FEATURE_VERSION } from "./features";

export interface BoundaryModel {
    /** Provenance, for humans. */
    trainedOn: string;
    /** Feature set and version the model was trained on (`features.ts`). */
    featureSet: string;
    featureVersion: number;
    /** The columns the model reads, by name, in its input order: a subset of `FEATURES`. */
    features: readonly string[];
    /** A line starts a new item when its probability is at least this. */
    threshold: number;
    /** Binary trees over `features`; class 1 is "starts an item". */
    model: PackedTreeModel<number> & Pick<ModelInfo, "featureVersion">;
}

/** Per model: the `FEATURES` column of each model input, and a reused input row. */
interface Columns {
    index: Int32Array;
    x: Float64Array;
}

const columnsCache = new WeakMap<BoundaryModel, Columns>();

/**
 * The model's input columns as indexes into `FEATURES`. Throws unless the
 * model was trained on this feature set and version and every column it
 * reads is one of the set's features (checked once per model).
 */
function modelColumns(model: BoundaryModel): Columns {
    let columns = columnsCache.get(model);
    if (columns) return columns;
    if (model.featureSet !== FEATURE_SET) {
        throw new Error(`Boundary model was trained on feature set "${model.featureSet}"; the runtime computes "${FEATURE_SET}"`);
    }
    if (model.featureVersion !== FEATURE_VERSION || model.model.featureVersion !== FEATURE_VERSION) {
        throw new Error(
            `Boundary model was trained on feature version ${model.featureVersion}; the runtime computes ${FEATURE_VERSION}`,
        );
    }
    if (model.model.format !== PACKED_TREES_FORMAT) {
        throw new Error(`Boundary model must be in ${PACKED_TREES_FORMAT}, got ${String(model.model.format)}`);
    }
    if (model.model.features.length !== model.features.length || model.model.features.some((f, k) => f !== model.features[k])) {
        throw new Error("Boundary model's trees read other columns than its feature list");
    }
    if (model.model.classes.length !== 2 || model.model.classes[1] !== 1) {
        throw new Error(`Boundary model must be binary with class 1 = start, got classes ${JSON.stringify(model.model.classes)}`);
    }
    if (!(model.threshold > 0 && model.threshold < 1)) {
        throw new Error(`Boundary model threshold must be in (0, 1), got ${model.threshold}`);
    }
    const byName = new Map<string, number>(FEATURES.map((name, k) => [name, k]));
    const index = new Int32Array(model.features.length);
    model.features.forEach((name, k) => {
        const column = byName.get(name);
        if (column === undefined) throw new Error(`Boundary model reads "${name}", which feature set ${FEATURE_SET} v${FEATURE_VERSION} lacks`);
        index[k] = column;
    });
    columns = { index, x: new Float64Array(index.length) };
    columnsCache.set(model, columns);
    return columns;
}

/** Throws unless `model` can run on the features the runtime computes. */
export function assertBoundaryModel(model: BoundaryModel): void {
    modelColumns(model);
}

/**
 * The model's input of a full feature row (`FEATURES` order), as a new
 * array; non-finite values are missing (NaN), as the training export writes
 * them.
 */
export function boundaryModelInput(model: BoundaryModel, row: ArrayLike<number>): number[] {
    const { index } = modelColumns(model);
    return Array.from(index, (column) => (Number.isFinite(row[column]) ? row[column] : NaN));
}

/** Probability that the line of a full feature row (`FEATURES` order) starts a new item. */
export function boundaryProbability(model: BoundaryModel, row: ArrayLike<number>): number {
    const { index, x } = modelColumns(model);
    for (let k = 0; k < index.length; k++) {
        const v = row[index[k]];
        x[k] = Number.isFinite(v) ? v : NaN;
    }
    return binaryProbability(model.model, x);
}
