/**
 * Item-type model runtime: one class per text item of a document.
 *
 * Stage 1 is a gradient-boosted tree ensemble over each item's item-type
 * features (`features.ts`). Stage 2 is another over the same features
 * followed by context features computed from the stage-1 probabilities of
 * every item of the document (`contextFeatures`): the item's own, its
 * neighbours' in document order, its page's mean, and the mean over the
 * document's items set in the same style. Both stages are multiclass models
 * of the shared runtime (`../models/runtime.ts`). Weights are generated by
 * beaver-extract-models (`bxm item-type export`) into `weights.ts`;
 * `contextFeatures` mirrors `tasks/item_type/context.py` there.
 *
 * Stage 2 corrects stage 1 from context. With `stage2.initFromStage1`, its
 * trees were trained on top of stage 1 (LightGBM `init_score`): an item's
 * stage-2 scores are its stage-2 tree scores plus its stage-1 raw scores, and
 * its stage-2 probabilities the softmax of that sum. When the export gives
 * `stage2.skipAbove`, an item whose largest stage-1 probability reaches it
 * keeps its stage-1 probabilities and stage 2 is not evaluated for it. Context
 * features come from stage-1 probabilities only, so skipping one item changes
 * no other item's result.
 */

import {
    assertModelFeatures,
    modelScores,
    PACKED_TREES_FORMAT,
    scoreProbabilities,
    type ModelInfo,
    type ModelInput,
    type PackedTreeModel,
} from "../models/runtime";
import type { DraftItemKind } from "../pipeline/draftItems";
import { FEATURES, FEATURE_SET, FEATURE_VERSION, itemTypeFeatures } from "./features";
import type { TypedDocument } from "./input";

export type ItemTypeClass = "caption" | "footnote" | "furniture" | "heading" | "reference" | "text";

type StageModel = PackedTreeModel<ItemTypeClass> & Pick<ModelInfo, "featureVersion">;

interface Stage2Model extends StageModel {
    /**
     * Scores start from the item's stage-1 raw scores (stage-1 baseline plus
     * trees, before the softmax) instead of from stage 2's own baseline alone.
     */
    initFromStage1?: boolean;
    /**
     * Largest stage-1 probability at or above which an item keeps its stage-1
     * probabilities. Omitted: stage 2 runs for every item.
     */
    skipAbove?: number;
}

export interface ItemTypeModel {
    /** Provenance, for humans. */
    trainedOn: string;
    /** Feature set and version both stages were trained on (`features.ts`). */
    featureSet: string;
    featureVersion: number;
    /** Class order of both stages' probabilities. */
    classes: readonly ItemTypeClass[];
    /** The draft kind each class is emitted as. */
    publicKind: Record<ItemTypeClass, DraftItemKind>;
    /** The stage-2 context definition, for humans; `contextFeatures` implements it. */
    context: { neighbors: readonly number[]; style: string; features: string };
    /** Over `FEATURES`. */
    stage1: StageModel;
    /** Over `FEATURES` followed by `contextFeatureNames(classes)`. */
    stage2: Stage2Model;
}

/** Offsets in document order of the neighbours whose stage-1 probabilities stage 2 reads. */
const NEIGHBORS = [-2, -1, 1, 2] as const;

/** Context feature names, in column order. */
export function contextFeatureNames(classes: readonly string[]): string[] {
    const names = classes.map((c) => `s1_${c}`);
    for (const off of NEIGHBORS) names.push(...classes.map((c) => `n${off > 0 ? "+" : ""}${off}_${c}`));
    names.push(...classes.map((c) => `page_${c}`), ...classes.map((c) => `style_${c}`), "style_log_n");
    return names;
}

/** A line as the context features read it. */
export interface ContextLine {
    font: string;
    /** Font size, as `items export` writes it (2 decimals). */
    size: number;
    /** Characters of the line's text (code points). */
    chars: number;
}

/** An item as the context features read it. */
export interface ContextUnit {
    /** Page index; units of one page share it. */
    page: number;
    lines: readonly ContextLine[];
}

/** Python's `round()`: halves go to the even neighbour. */
function roundHalfEven(x: number): number {
    const r = Math.round(x);
    return Math.abs(x % 1) === 0.5 && r % 2 !== 0 ? r - 1 : r;
}

/**
 * The (font, size rounded to the nearest 0.5) pair covering most characters
 * of the unit's lines, first seen on ties; "" for a unit without lines.
 */
function unitStyle(unit: ContextUnit): string {
    const weight = new Map<string, number>();
    for (const line of unit.lines) {
        const key = `${line.font}|${roundHalfEven(line.size * 2) / 2}`;
        weight.set(key, (weight.get(key) ?? 0) + line.chars);
    }
    let best = "";
    let most = -1;
    for (const [key, n] of weight) {
        if (n > most) {
            most = n;
            best = key;
        }
    }
    return best;
}

/** Per unit: the mean of `proba` over the units of its group, and the group's size. */
function groupMeans(proba: readonly (readonly number[])[], groups: readonly string[]): { mean: number[][]; n: number[] } {
    const c = proba[0]?.length ?? 0;
    const sums = new Map<string, { sum: number[]; n: number }>();
    proba.forEach((p, i) => {
        let group = sums.get(groups[i]);
        if (!group) {
            group = { sum: new Array<number>(c).fill(0), n: 0 };
            sums.set(groups[i], group);
        }
        for (let k = 0; k < c; k++) group.sum[k] += p[k];
        group.n++;
    });
    const mean: number[][] = [];
    const n: number[] = [];
    for (const key of groups) {
        const group = sums.get(key)!;
        mean.push(group.sum.map((s) => s / group.n));
        n.push(group.n);
    }
    return { mean, n };
}

/**
 * Stage-2 context features (`contextFeatureNames` columns) of every unit of
 * one document, from the units' stage-1 probabilities. `units` and `proba`
 * are in document order: pages in order, units in page order. Neighbours past
 * the document's start or end are NaN.
 */
export function contextFeatures(units: readonly ContextUnit[], proba: readonly (readonly number[])[]): number[][] {
    const n = units.length;
    const c = proba[0]?.length ?? 0;
    const missing = new Array<number>(c).fill(NaN);
    const page = groupMeans(proba, units.map((u) => String(u.page)));
    const style = groupMeans(proba, units.map(unitStyle));
    const rows: number[][] = [];
    for (let i = 0; i < n; i++) {
        const row = [...proba[i]];
        for (const off of NEIGHBORS) {
            const j = i + off;
            row.push(...(j >= 0 && j < n ? proba[j] : missing));
        }
        row.push(...page.mean[i], ...style.mean[i], Math.log1p(style.n[i]));
        rows.push(row);
    }
    return rows;
}

/** Characters of a text as Python counts them (code points). */
function codePoints(text: string): number {
    let n = 0;
    for (let i = 0; i < text.length; i++) {
        const code = text.charCodeAt(i);
        if (code >= 0xd800 && code <= 0xdbff && i + 1 < text.length) {
            const next = text.charCodeAt(i + 1);
            if (next >= 0xdc00 && next <= 0xdfff) i++;
        }
        n++;
    }
    return n;
}

/** The context units of a document, in document order. */
export function contextUnits(doc: TypedDocument): ContextUnit[] {
    const units: ContextUnit[] = [];
    for (const page of doc.pages) {
        for (const item of page.items) {
            units.push({
                page: page.pageIndex,
                lines: item.lines.map((line) => ({ font: line.font, size: line.size, chars: codePoints(line.text) })),
            });
        }
    }
    return units;
}

const checked = new WeakSet<ItemTypeModel>();

/** Throws unless both stages were trained on the features the runtime computes. */
export function assertItemTypeModel(model: ItemTypeModel): void {
    if (checked.has(model)) return;
    if (model.featureSet !== FEATURE_SET) {
        throw new Error(`Item-type model was trained on feature set "${model.featureSet}"; the runtime computes "${FEATURE_SET}"`);
    }
    assertModelFeatures(model.stage1, FEATURE_VERSION, FEATURES, "Item-type stage-1");
    assertModelFeatures(model.stage2, FEATURE_VERSION, [...FEATURES, ...contextFeatureNames(model.classes)], "Item-type stage-2");
    for (const stage of [model.stage1, model.stage2]) {
        if (stage.format !== PACKED_TREES_FORMAT) {
            throw new Error(`Item-type model stages must be in ${PACKED_TREES_FORMAT}, got ${String(stage.format)}`);
        }
        if (stage.classes.length !== model.classes.length || stage.classes.some((c, k) => c !== model.classes[k])) {
            throw new Error("Item-type model stages disagree on the class order");
        }
    }
    const { skipAbove, initFromStage1 } = model.stage2;
    if (skipAbove !== undefined && !(skipAbove > 0 && skipAbove <= 1)) {
        throw new Error(`Item-type stage-2 skipAbove must be in (0, 1], got ${skipAbove}`);
    }
    if (initFromStage1 !== undefined && typeof initFromStage1 !== "boolean") {
        throw new Error(`Item-type stage-2 initFromStage1 must be a boolean, got ${String(initFromStage1)}`);
    }
    checked.add(model);
}

/**
 * Stage-2 probabilities of one item's stage-2 row, given its stage-1 raw
 * scores: the softmax of the stage-2 scores, to which `initFromStage1` adds
 * the stage-1 scores after the stage-2 trees, as the training code does.
 */
export function stage2Probabilities(model: ItemTypeModel, x: ModelInput, stage1Scores: readonly number[]): number[] {
    const scores = modelScores(model.stage2, x);
    if (model.stage2.initFromStage1) for (let k = 0; k < scores.length; k++) scores[k] += stage1Scores[k];
    return scoreProbabilities(scores);
}

/** Time each part of `classifyItemTypes` took, in ms. */
export interface ItemTypeTimings {
    featuresMs: number;
    stage1Ms: number;
    contextMs: number;
    stage2Ms: number;
}

export interface ItemTypeResult {
    /**
     * Class probabilities per page and item, in `model.classes` order:
     * stage 2's, or stage 1's for an item stage 2 skips (`skipAbove`).
     */
    probs: number[][][];
    /** Most probable class per page and item. */
    classes: ItemTypeClass[][];
    timings: ItemTypeTimings;
}

/** Missing values are NaN to the trees; the training export writes every non-finite value as missing. */
const finiteOrNaN = (v: number) => (Number.isFinite(v) ? v : NaN);

/** Index of the largest value, the first on ties (`numpy.argmax`). */
export function argmax(values: readonly number[]): number {
    let best = 0;
    for (let k = 1; k < values.length; k++) if (values[k] > values[best]) best = k;
    return best;
}

/** Class probabilities and the most probable class of every item of a document. */
export function classifyItemTypes(doc: TypedDocument, model: ItemTypeModel): ItemTypeResult {
    assertItemTypeModel(model);
    const t0 = performance.now();
    // One row per item holds the stage-2 input: the item-type features, then
    // the context features once stage 1 has run. Stage 1 reads the head only.
    const width = model.stage2.features.length;
    const rows = itemTypeFeatures(doc)
        .flat()
        .map((features) => {
            const row = new Float64Array(width);
            for (let j = 0; j < features.length; j++) row[j] = finiteOrNaN(features[j]);
            return row;
        });
    const t1 = performance.now();
    // Raw scores are kept: stage 2 may start from them (`initFromStage1`).
    const s1 = rows.map((x) => modelScores(model.stage1, x));
    const p1 = s1.map(scoreProbabilities);
    const t2 = performance.now();
    const context = contextFeatures(contextUnits(doc), p1);
    rows.forEach((row, i) => row.set(context[i], FEATURES.length));
    const t3 = performance.now();
    const { skipAbove } = model.stage2;
    const p2 = rows.map((x, i) =>
        skipAbove !== undefined && Math.max(...p1[i]) >= skipAbove ? p1[i] : stage2Probabilities(model, x, s1[i]),
    );
    const t4 = performance.now();
    const probs: number[][][] = [];
    const classes: ItemTypeClass[][] = [];
    let k = 0;
    for (const page of doc.pages) {
        const pageProbs = p2.slice(k, k + page.items.length);
        k += page.items.length;
        probs.push(pageProbs);
        classes.push(pageProbs.map((p) => model.classes[argmax(p)]));
    }
    return {
        probs,
        classes,
        timings: { featuresMs: t1 - t0, stage1Ms: t2 - t1, contextMs: t3 - t2, stage2Ms: t4 - t3 },
    };
}
