/**
 * Hook to register an MCP (Model Context Protocol) server on Zotero's HTTP server.
 *
 * When the `mcpServerEnabled` preference is true, this hook creates an MCPService,
 * registers all tools, and mounts the /beaver/mcp endpoint.
 * The endpoint speaks JSON-RPC 2.0 (MCP Streamable HTTP transport), so any MCP
 * client (Claude Code, Claude Desktop via mcp-remote, Cursor) can call the tools.
 *
 * Tools: search_by_topic, search_by_metadata, read_attachment, read_note,
 *        get_item_details, list_collections, list_tags, list_items
 * Optional tool: create_note
 */

import { useEffect } from 'react';
import { useAtomValue } from 'jotai';
import { MCPService } from '../../src/services/mcpService';
import {
    handleItemSearchByTopicRequest,
    handleItemSearchByMetadataRequest,
    handleZoteroDocumentRequest,
    handleGetMetadataRequest,
    handleListCollectionsRequest,
    handleListTagsRequest,
    handleListItemsRequest,
    handleReadNoteRequest,
    validateCreateNoteAction,
    executeCreateNoteAction,
} from '../../src/services/agentDataProvider';
import type { TimeoutContext } from '../../src/services/agentDataProvider/timeout';
import { getCitationKeyFromItem, getZoteroSelectURI } from '../../src/utils/zoteroUtils';
import { libraryRefForLibraryID } from '../../src/utils/libraryIdentity';
import { logger } from '../../src/utils/logger';
import { isAuthenticatedAtom } from '../atoms/auth';
import { mcpCreateNoteToolEnabledAtom, mcpServerEnabledAtom } from '../atoms/ui';
import { store } from '../store';
import type {
    WSItemSearchByTopicRequest,
    WSItemSearchByTopicResponse,
    WSItemSearchByMetadataRequest,
    WSItemSearchByMetadataResponse,
    WSZoteroDocumentRequest,
    WSZoteroDocumentResponse,
    WSGetMetadataRequest,
    WSGetMetadataResponse,
    WSListCollectionsRequest,
    WSListCollectionsResponse,
    WSListTagsRequest,
    WSListTagsResponse,
    WSListItemsRequest,
    WSListItemsResponse,
    WSReadNoteRequest,
    WSReadNoteResponse,
    WSAgentActionValidateRequest,
    WSAgentActionExecuteRequest,
    WSAgentActionExecuteResponse,
    RegularListResultItem,
    NoteResultItem,
    AttachmentRowResult,
    ZoteroItemCategory,
    ItemSearchFrontendResultItem,
} from '../../src/services/agentProtocol';

// =============================================================================
// MCP stdio bridge script
// =============================================================================

/**
 * Standalone Node.js script that bridges MCP stdio transport to Beaver's HTTP
 * endpoint. Written to the Zotero data directory when MCP is enabled.
 * MCP clients like Claude Desktop launch this as a subprocess.
 */
const MCP_BRIDGE_SCRIPT = String.raw`#!/usr/bin/env node
// Beaver MCP stdio bridge
// Connects MCP clients (e.g. Claude Desktop) to Beaver's HTTP endpoint in Zotero.
// Auto-generated by Beaver. Do not edit; it may be overwritten on updates.
//
// Usage: node beaver-mcp-stdio.mjs [port]
//
import { createInterface } from "node:readline";
import { request } from "node:http";

const PORT = process.argv[2] || process.env.BEAVER_MCP_PORT || "23119";

function post(body) {
  return new Promise((resolve, reject) => {
    const req = request({
      hostname: "127.0.0.1",
      port: PORT,
      path: "/beaver/mcp",
      method: "POST",
      headers: { "Content-Type": "application/json", "Accept": "application/json", "Content-Length": Buffer.byteLength(body) },
    }, (res) => {
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => resolve(data));
    });
    req.on("error", reject);
    req.write(body);
    req.end();
  });
}

const rl = createInterface({ input: process.stdin, terminal: false });

rl.on("line", async (line) => {
  if (!line.trim()) return;
  let msg;
  try {
    msg = JSON.parse(line);
  } catch {
    return;
  }

  const isNotification = msg.id === undefined || msg.id === null;

  try {
    const response = await post(line);
    if (!isNotification && response) {
      process.stdout.write(response + "\n");
    }
  } catch (err) {
    if (!isNotification) {
      process.stdout.write(JSON.stringify({
        jsonrpc: "2.0",
        id: msg.id,
        error: {
          code: -32000,
          message: "Cannot reach Beaver in Zotero. Is Zotero running? (" + err.message + ")",
        },
      }) + "\n");
    }
  }
});

rl.on("close", () => process.exit(0));
`;

/**
 * Returns the path where the bridge script is (or will be) written.
 */
export function getMcpBridgeScriptPath(): string {
    return PathUtils.join(Zotero.DataDirectory.dir, 'beaver-mcp-stdio.mjs');
}

/**
 * Write the stdio bridge script to disk and return its absolute path.
 */
export async function ensureMcpBridgeScript(): Promise<string> {
    const scriptPath = getMcpBridgeScriptPath();
    await IOUtils.writeUTF8(scriptPath, MCP_BRIDGE_SCRIPT);
    return scriptPath;
}

// =============================================================================
// Tool definitions
// =============================================================================

const SEARCH_BY_TOPIC_TOOL = {
    name: 'search_by_topic',
    annotations: {
        title: 'Search Library by Topic',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
    },
    description:
        "Search the user's Zotero reference library by research topic using semantic similarity. " +
        'Returns papers whose content is conceptually related to the query, ranked by relevance. ' +
        'Use this to explore what the user has collected on a subject, build literature reviews, or find relevant background reading. ' +
        'Each result includes an item ID and attachment IDs that can be used with `read_attachment` to read full-text content. ' +
        'Only attachments with `status: "available"` can be read.',
    inputSchema: {
        type: 'object' as const,
        properties: {
            topic_query: {
                type: 'string',
                description:
                    'A concise topic phrase (2–8 words) describing the research concept. Use canonical academic terms. ' +
                    'Examples: "gender gap in STEM", "institutions and economic development", "climate-induced migration".',
            },
            author_filter: {
                type: 'array',
                items: { type: 'string' },
                description: 'Author last names to filter results (OR logic). Example: ["Acemoglu", "Robinson"].',
            },
            min_year: {
                type: 'integer',
                description: 'Earliest publication year (inclusive).',
            },
            max_year: {
                type: 'integer',
                description: 'Latest publication year (inclusive).',
            },
            libraries_filter: {
                type: 'array',
                items: { type: 'string' },
                description: 'Library names or IDs to restrict the search scope.',
            },
            tags_filter: {
                type: 'array',
                items: { type: 'string' },
                description: 'Zotero tags to filter results (OR logic).',
            },
            collections_filter: {
                type: 'array',
                items: { type: 'string' },
                description: 'Collection names or keys to filter results (OR logic).',
            },
            limit: {
                type: 'integer',
                description: 'Max results per page (default 5, max 25).',
                default: 5,
            },
            offset: {
                type: 'integer',
                description: 'Results to skip for pagination (default 0).',
                default: 0,
            },
        },
        required: ['topic_query'],
    },
};

const SEARCH_BY_METADATA_TOOL = {
    name: 'search_by_metadata',
    annotations: {
        title: 'Search Library by Metadata',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
    },
    description:
        "Search the user's Zotero reference library by bibliographic metadata: author name, title keywords, " +
        'or publication/journal name. At least one search field must be provided. Use this when you know specific ' +
        'details about the paper(s) you\'re looking for, such as an author name or title fragment. ' +
        'For conceptual/topic-based discovery, use `search_by_topic` instead. ' +
        'Each result includes attachment IDs that can be used with `read_attachment` to read full-text content. ' +
        'Only attachments with `status: "available"` can be read.',
    inputSchema: {
        type: 'object' as const,
        properties: {
            author_query: {
                type: 'string',
                description: 'Author\'s last name to search for (e.g., "Acemoglu").',
            },
            title_query: {
                type: 'string',
                description: 'Keyword or phrase from the title (e.g., "colonial origins").',
            },
            publication_query: {
                type: 'string',
                description: 'Journal or publication name (e.g., "American Economic Review").',
            },
            min_year: {
                type: 'integer',
                description: 'Earliest publication year (inclusive).',
            },
            max_year: {
                type: 'integer',
                description: 'Latest publication year (inclusive).',
            },
            libraries_filter: {
                type: 'array',
                items: { type: 'string' },
                description: 'Library names or IDs to restrict the search scope.',
            },
            tags_filter: {
                type: 'array',
                items: { type: 'string' },
                description: 'Zotero tags to filter results (OR logic).',
            },
            collections_filter: {
                type: 'array',
                items: { type: 'string' },
                description: 'Collection names or keys to filter results (OR logic).',
            },
            limit: {
                type: 'integer',
                description: 'Max results per page (default 5, max 25).',
                default: 5,
            },
            offset: {
                type: 'integer',
                description: 'Results to skip for pagination (default 0).',
                default: 0,
            },
        },
        required: [],
    },
};

const READ_ATTACHMENT_TOOL = {
    name: 'read_attachment',
    annotations: {
        title: 'Read Attachment',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
    },
    description:
        "Read the text content of a PDF or EPUB attachment from the user's Zotero library. " +
        'Extracts and returns text from specified PDF pages or EPUB sections (or the first 30 if no range is given). ' +
        'The `attachment_id` must be obtained from another tool: use `search_by_topic` or `search_by_metadata` ' +
        '(which include attachment IDs in results), or call `get_item_details` with `include_attachments: true`. ' +
        'For long documents, read progressively by specifying page ranges. For EPUBs, page numbers mean 1-based section ordinals. ' +
        'Only PDF and EPUB attachments with `status: "available"` are supported.',
    inputSchema: {
        type: 'object' as const,
        properties: {
            attachment_id: {
                type: 'string',
                description:
                    'The attachment ID in format `<library_id>-<zotero_key>` (e.g., "1-ABC12345"). Obtain this from search results.',
            },
            start_page: {
                type: 'integer',
                description: 'Starting page number (1-indexed). For EPUBs, this is the section ordinal. Defaults to page 1.',
            },
            end_page: {
                type: 'integer',
                description: 'Ending page number (inclusive). For EPUBs, this is the section ordinal. Defaults to the last page. Maximum 30 pages per request.',
            },
        },
        required: ['attachment_id'],
    },
};

const READ_NOTE_TOOL = {
    name: 'read_note',
    annotations: {
        title: 'Read Note',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
    },
    description:
        "Read a Zotero note's content from the user's library as simplified HTML. " +
        'Use note IDs returned by `get_item_details` with `include_notes: true`, or by search/list tools. ' +
        'The simplified format represents citations, annotations, and images as self-closing tags. ' +
        'Use `offset` and `limit` to page through long notes by line.',
    inputSchema: {
        type: 'object' as const,
        properties: {
            note_id: {
                type: 'string',
                description:
                    'The note ID in format `<library_id>-<zotero_key>` (e.g., "1-ABC12345"). Obtain this from tool results.',
            },
            offset: {
                type: 'integer',
                description: 'Optional 1-indexed start line. Defaults to the beginning of the note.',
            },
            limit: {
                type: 'integer',
                description: 'Optional maximum number of lines to return.',
            },
        },
        required: ['note_id'],
    },
};

const CREATE_NOTE_TOOL = {
    name: 'create_note',
    annotations: {
        title: 'Create Zotero Note',
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false,
    },
    description:
        "Create a Zotero note from markdown in the user's library. " +
        'Content supports `<citation>` tags: use `<citation id="libraryID-zoteroKey"/>`, optionally with page locators such as `loc="page5"` or `loc="page5-page6"`. ' +
        'Use the 1-based page numbers from `read_attachment` `<pageN>` tags (physical page index, not printed labels). ' +
        'Only use citation IDs returned by this session\'s tool results; never construct or guess IDs. ' +
        'Copy page locators verbatim from `read_note` when editing existing notes; omit `loc` for metadata-only citations. ' +
        'Do not use legacy citation attributes such as `item_id`, `att_id`, `page`, or `sid`.',
    inputSchema: {
        type: 'object' as const,
        properties: {
            title: {
                type: 'string',
                description: 'Concise note title. Prefer short titles, roughly 35 characters or fewer.',
            },
            content: {
                type: 'string',
                description:
                    'Markdown content with `<citation>` tags, e.g. `<citation id="1-ABC12345" loc="page5"/>`. Use IDs and locators from tool results only.',
            },
            parent_id: {
                type: 'string',
                description:
                    'Optional parent item ID in `<library_id>-<zotero_key>` format. Creates the note as a child of that item.',
            },
            library: {
                type: 'string',
                description: 'Optional target library name or ID. Omit to use the default user library.',
            },
            collection: {
                type: 'string',
                description:
                    'Optional collection name or key for standalone notes. Ignored when `parent_id` is set because child notes inherit the parent item location.',
            },
        },
        required: ['title', 'content'],
    },
};

const GET_ITEM_DETAILS_TOOL = {
    name: 'get_item_details',
    annotations: {
        title: 'Get Item Details',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
    },
    description:
        "Get complete bibliographic metadata for specific items in the user's Zotero library. " +
        'Returns all Zotero fields for each item (title, authors, abstract, DOI, journal, volume, issue, pages, date, etc.), ' +
        'along with tags and collection memberships. Use this to get detailed metadata after finding items via search, ' +
        'or to look up specific fields like DOI or abstract. ' +
        'Set `include_attachments` to true to also see which files are attached and their availability status. ' +
        'Set `include_notes` to true to also fetch the child notes attached to each item.',
    inputSchema: {
        type: 'object' as const,
        properties: {
            item_ids: {
                type: 'array',
                items: { type: 'string' },
                description:
                    'Item IDs in format `<library_id>-<zotero_key>` (e.g., ["1-ABC12345"]). Maximum 25 items.',
            },
            include_attachments: {
                type: 'boolean',
                description: 'Whether to include attachment metadata (filenames, types, availability). Default: false.',
                default: false,
            },
            include_notes: {
                type: 'boolean',
                description: 'Whether to include child notes (title, parent item, last modified) for each item. Default: false.',
                default: false,
            },
        },
        required: ['item_ids'],
    },
};

const LIST_COLLECTIONS_TOOL = {
    name: 'list_collections',
    annotations: {
        title: 'List Collections',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
    },
    description:
        "List collections (folders) in the user's Zotero library to understand how their references are organized. " +
        'Returns collection names, keys, item counts, and subcollection counts. ' +
        'Use the collection keys or names as filters in search tools (`collections_filter`), ' +
        'or set `parent_collection` to explore nested subcollections. ' +
        'Useful for understanding the scope and organization of the library before searching.',
    inputSchema: {
        type: 'object' as const,
        properties: {
            library: {
                type: 'string',
                description: "Library name or ID. Omit to use the user's default library.",
            },
            parent_collection: {
                type: 'string',
                description: 'Collection key to list subcollections within. Omit for top-level collections.',
            },
            include_item_counts: {
                type: 'boolean',
                description: 'Whether to include the number of items in each collection. Default: true.',
                default: true,
            },
            limit: {
                type: 'integer',
                description: 'Max results per page (default 50, max 100).',
                default: 50,
            },
            offset: {
                type: 'integer',
                description: 'Results to skip for pagination (default 0).',
                default: 0,
            },
        },
        required: [],
    },
};

const LIST_TAGS_TOOL = {
    name: 'list_tags',
    annotations: {
        title: 'List Tags',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
    },
    description:
        "List tags in the user's Zotero library. " +
        'Tags are user-defined labels attached to references (e.g., "to-read", "methods", "key-paper"). ' +
        'Returns tag names with per-type counts: item_count (regular items), attachment_count, note_count, and annotation_count. ' +
        'Use this to discover available tags before using them as filters in `search_by_topic` or `search_by_metadata` (`tags_filter`). ' +
        'Set `min_item_count` to filter out rarely-used tags (counts all tagged objects, not just regular items).',
    inputSchema: {
        type: 'object' as const,
        properties: {
            library: {
                type: 'string',
                description: "Library name or ID. Omit to use the user's default library.",
            },
            collection: {
                type: 'string',
                description: 'Collection key to list tags within that collection only.',
            },
            min_item_count: {
                type: 'integer',
                description: 'Minimum number of items a tag must have to be included. Default: 1.',
                default: 1,
            },
            limit: {
                type: 'integer',
                description: 'Max results per page (default 50, max 100).',
                default: 50,
            },
            offset: {
                type: 'integer',
                description: 'Results to skip for pagination (default 0).',
                default: 0,
            },
        },
        required: [],
    },
};

const LIST_ITEMS_TOOL = {
    name: 'list_items',
    annotations: {
        title: 'List Items',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
    },
    description:
        "Browse items in the user's Zotero library, optionally filtered by collection and/or tag. " +
        'Unlike the search tools, this does not require a query — it simply lists items matching the given filters, ' +
        'sorted by the specified field. Use this to enumerate what\'s in a specific collection, find recently added items, ' +
        'or get an overview of items with a particular tag. ' +
        'Filters are cumulative: specifying both collection and tag returns only items matching both criteria. ' +
        'By default only regular bibliographic items are returned; use `item_category` to list notes, attachments, ' +
        'or all supported item types instead. ' +
        'Note: for regular items this tool returns lightweight metadata without attachment IDs. ' +
        'To read an item\'s PDF or EPUB, first call `get_item_details` with `include_attachments: true` to obtain the attachment ID, ' +
        'then call `read_attachment`.',
    inputSchema: {
        type: 'object' as const,
        properties: {
            library: {
                type: 'string',
                description: "Library name or ID. Omit to use the user's default library.",
            },
            collection: {
                type: 'string',
                description: 'Collection name or key to list items from.',
            },
            tag: {
                type: 'string',
                description: 'Tag to filter items by.',
            },
            item_category: {
                type: 'string',
                enum: ['regular', 'note', 'attachment', 'all'],
                description:
                    'Item type to return: "regular" (bibliographic items), "note", "attachment", or "all" (regular items, notes, and attachments). Default: "regular".',
                default: 'regular',
            },
            recursive: {
                type: 'boolean',
                description: 'Include items from subcollections. Default: true.',
                default: true,
            },
            sort_by: {
                type: 'string',
                description:
                    'Sort field: "dateAdded", "dateModified", "title", "creator", or "year". Default: "dateModified".',
                default: 'dateModified',
            },
            sort_order: {
                type: 'string',
                description: '"asc" or "desc". Default: "desc".',
                default: 'desc',
            },
            limit: {
                type: 'integer',
                description: 'Max results per page (default 20, max 100).',
                default: 20,
            },
            offset: {
                type: 'integer',
                description: 'Results to skip for pagination (default 0).',
                default: 0,
            },
        },
        required: [],
    },
};

// =============================================================================
// Utilities
// =============================================================================

function generateRequestId(): string {
    if (typeof Zotero !== 'undefined' && Zotero.Utilities?.randomString) {
        return Zotero.Utilities.randomString(16);
    }
    return `${Date.now()}-${Math.random().toString(36).substring(2, 10)}`;
}

function parseItemId(itemId: string | null | undefined): { libraryId: number; key: string } | null {
    if (!itemId) return null;
    const dashIndex = itemId.indexOf('-');
    if (dashIndex === -1) return null;
    const libraryId = parseInt(itemId.substring(0, dashIndex), 10);
    const key = itemId.substring(dashIndex + 1);
    if (isNaN(libraryId) || !key) return null;
    return { libraryId, key };
}

function getMcpAttachmentId(attachment: any): string | null {
    if (attachment.attachment_id) return attachment.attachment_id;
    if (attachment.item_id) return attachment.item_id;
    if (attachment.attachment?.library_id != null && attachment.attachment?.zotero_key) {
        return `${attachment.attachment.library_id}-${attachment.attachment.zotero_key}`;
    }
    return null;
}

function getMcpAttachmentStatus(attachment: any): string {
    const status = attachment.status ?? attachment.file_status?.status;
    if (status === 'readable') return 'available';
    if (status === 'unreadable') return 'unavailable';
    if (status) return status;
    return attachment.path ? 'available' : 'unavailable';
}

function mcpError(message: string) {
    return {
        content: [{ type: 'text', text: message }],
        isError: true,
    };
}

type McpToolRegistration = {
    def: {
        name: string;
        description: string;
        inputSchema: Record<string, any>;
        annotations?: Record<string, any>;
    };
    handler: (args: any) => Promise<any>;
};

// =============================================================================
// Response formatting: search results
// =============================================================================

/**
 * Format authors from serialized ItemData creators into "LastName, LastName & LastName".
 */
function formatAuthors(
    creators?: { first_name?: string | null; last_name?: string | null }[] | null,
): string {
    if (!creators || creators.length === 0) return 'Unknown';
    const names = creators
        .map((c) => c.last_name || c.first_name || null)
        .filter((n): n is string => n !== null);
    if (names.length === 0) return 'Unknown';
    if (names.length === 1) return names[0];
    if (names.length === 2) return `${names[0]} & ${names[1]}`;
    return `${names.slice(0, -1).join(', ')} & ${names[names.length - 1]}`;
}

/**
 * Normalize tags from various formats to a string array.
 */
function normalizeTags(tags: any[] | null | undefined): string[] {
    if (!tags || tags.length === 0) return [];
    return tags
        .map((t: any) => (typeof t === 'string' ? t : t.tag ?? t.name ?? ''))
        .filter(Boolean);
}

/**
 * Transform an ItemSearchFrontendResultItem to the compact MCP search result format.
 */
function formatSearchResultItem(entry: ItemSearchFrontendResultItem, includeSimilarity: boolean): any {
    const item = entry.item;
    const result: any = {
        item_id: `${item.library_id}-${item.zotero_key}`,
        item_type: item.item_type,
        title: item.title ?? 'Untitled',
        authors: formatAuthors(item.creators),
        year: item.year ?? null,
        publication: item.publication_title ?? null,
    };

    const zoteroUri = getZoteroSelectURI(item.library_id, item.zotero_key);
    if (zoteroUri) result.zotero_uri = zoteroUri;

    if (includeSimilarity && entry.similarity != null) {
        result.similarity = Math.round(entry.similarity * 100) / 100;
    }

    if (item.citation_key) {
        result.citation_key = item.citation_key;
    }

    // Abstract truncated to ~300 chars
    if (item.abstract) {
        result.abstract = item.abstract.length > 300
            ? item.abstract.slice(0, 300) + '...'
            : item.abstract;
    }

    const tags = normalizeTags(item.tags);
    if (tags.length > 0) result.tags = tags;

    // Compact attachment format
    if (entry.attachments && entry.attachments.length > 0) {
        result.attachments = entry.attachments.map((a: any) => ({
            attachment_id: getMcpAttachmentId(a),
            filename: a.filename ?? a.attachment?.filename ?? null,
            content_kind: a.content_kind ?? null,
            page_count: a.page_count ?? a.file_status?.page_count ?? null,
            line_count: a.line_count ?? null,
            annotations_count: a.annotations_count ?? a.attachment?.annotations_count ?? null,
            status: getMcpAttachmentStatus(a),
            status_reason: a.status_reason ?? a.file_status?.status_reason ?? null,
        }));
    }

    return result;
}

// =============================================================================
// Tool handlers
// =============================================================================

async function handleSearchByTopic(args: any): Promise<any> {
    const limit = Math.min(Math.max(1, args.limit ?? 5), 25);
    const offset = Math.max(0, args.offset ?? 0);

    const wsRequest: WSItemSearchByTopicRequest = {
        event: 'item_search_by_topic_request',
        request_id: generateRequestId(),
        topic_query: args.topic_query,
        author_filter: args.author_filter,
        year_min: args.min_year,
        year_max: args.max_year,
        libraries_filter: args.libraries_filter,
        tags_filter: args.tags_filter,
        collections_filter: args.collections_filter,
        limit: limit + 1,
        offset,
    };

    const response: WSItemSearchByTopicResponse = await handleItemSearchByTopicRequest(wsRequest);

    if (response.error) {
        return mcpError(`Search failed: ${response.error}`);
    }

    const hasMore = response.items.length > limit;
    const items = hasMore ? response.items.slice(0, limit) : response.items;

    return {
        has_more: hasMore,
        next_offset: hasMore ? offset + limit : null,
        results: items.map((item) => formatSearchResultItem(item, true)),
    };
}

async function handleSearchByMetadata(args: any): Promise<any> {
    const hasQuery = !!args.author_query || !!args.title_query || !!args.publication_query;
    if (!hasQuery) {
        return mcpError(
            'At least one search field must be provided: author_query, title_query, or publication_query.',
        );
    }

    const limit = Math.min(Math.max(1, args.limit ?? 5), 25);
    const offset = Math.max(0, args.offset ?? 0);

    const wsRequest: WSItemSearchByMetadataRequest = {
        event: 'item_search_by_metadata_request',
        request_id: generateRequestId(),
        title_query: args.title_query,
        author_query: args.author_query,
        publication_query: args.publication_query,
        year_min: args.min_year,
        year_max: args.max_year,
        libraries_filter: args.libraries_filter,
        tags_filter: args.tags_filter,
        collections_filter: args.collections_filter,
        limit: limit + 1,
        offset,
    };

    const response: WSItemSearchByMetadataResponse = await handleItemSearchByMetadataRequest(wsRequest);

    if (response.error) {
        return mcpError(`Search failed: ${response.error}`);
    }

    const hasMore = response.items.length > limit;
    const items = hasMore ? response.items.slice(0, limit) : response.items;

    return {
        has_more: hasMore,
        next_offset: hasMore ? offset + limit : null,
        results: items.map((item) => formatSearchResultItem(item, false)),
    };
}

/**
 * Handler for the MCP `read_attachment` tool.
 *
 * Exported so the dev-only `/beaver/test/read-attachment` endpoint can
 * exercise the exact tool code path (page-argument validation, document
 * request, page-window slicing) in automated tests.
 */
export async function handleReadAttachment(args: any): Promise<any> {
    const MAX_PAGES = 30;

    const parsed = parseItemId(args.attachment_id);
    if (!parsed) {
        return mcpError(
            `Invalid attachment_id format: "${args.attachment_id}". Expected format: <library_id>-<zotero_key> (e.g., "1-ABC12345").`,
        );
    }

    const startPage = args.start_page ?? 1;
    if (!Number.isInteger(startPage) || startPage < 1) {
        return mcpError('start_page must be a positive integer.');
    }

    const requestedEndPage = args.end_page ?? (startPage + MAX_PAGES - 1);
    if (!Number.isInteger(requestedEndPage) || requestedEndPage < 1) {
        return mcpError('end_page must be a positive integer.');
    }
    if (requestedEndPage < startPage) {
        return mcpError('end_page must be greater than or equal to start_page.');
    }

    const endPage = args.end_page != null
        ? Math.min(requestedEndPage, startPage + MAX_PAGES - 1)
        : startPage + MAX_PAGES - 1;

    const wsRequest: WSZoteroDocumentRequest = {
        event: 'zotero_document_request',
        request_id: generateRequestId(),
        attachment: {
            library_id: parsed.libraryId,
            zotero_key: parsed.key,
            library_ref: libraryRefForLibraryID(parsed.libraryId) ?? undefined,
        },
        mode: 'markdown',
    };

    const response: WSZoteroDocumentResponse = await handleZoteroDocumentRequest(wsRequest);

    if (response.error || !response.result) {
        return mcpError(response.error ?? 'Failed to read attachment');
    }
    const result = response.result;
    const markdownDocument = result.content_kind === 'epub' || result.content_kind === 'snapshot'
        ? domDocumentToMarkdownPages(result)
        : result.content_kind === 'text'
            ? null
            : result.mode === 'markdown'
                ? {
                    pageCount: result.document.pageCount,
                    pages: result.document.pages.map((page) => ({
                        pageNumber: page.index + 1,
                        markdown: page.markdown ?? '',
                    })),
                }
                : null;
    if (!markdownDocument) {
        return mcpError('Attachment read returned an unsupported document format.');
    }

    const totalPages = markdownDocument.pageCount;
    if (Number.isInteger(totalPages) && totalPages >= 0 && startPage > totalPages) {
        return mcpError(`Requested start_page ${startPage} is out of range; attachment has ${totalPages} pages.`);
    }

    const requestedPages = markdownDocument.pages.filter(
        (page) => page.pageNumber >= startPage && page.pageNumber <= endPage,
    );
    if (requestedPages.length === 0) {
        return mcpError(`Requested page window ${startPage}-${endPage} is out of range or contains no extractable pages.`);
    }

    // Build plain text response with <pageN> tags
    const actualEnd = requestedPages.length > 0
        ? requestedPages[requestedPages.length - 1].pageNumber
        : startPage;
    const header = `Attachment: ${args.attachment_id} | Total pages: ${markdownDocument.pageCount ?? 'unknown'} | Showing pages ${startPage}-${actualEnd}`;
    const pageTexts = requestedPages.map(
        (p) => `<page${p.pageNumber}>\n${p.markdown}\n</page${p.pageNumber}>`,
    );

    return [header, '', ...pageTexts].join('\n');
}

interface AttachmentMarkdownPage {
    pageNumber: number;
    markdown: string;
}

type DomReadItem = {
    kind: string;
    sectionIndex: number;
    order: number;
    text?: string;
    level?: number;
    sentences?: Array<{ text: string }>;
    pageNumber?: number;
};

// EPUB and snapshot both carry stamped per-item page numbers. Grouping items by
// that coordinate keeps MCP reads aligned with backend read pagination.
function domDocumentToMarkdownPages(
    document: Extract<NonNullable<WSZoteroDocumentResponse['result']>, { content_kind: 'epub' | 'snapshot' }>,
): { pageCount: number; pages: AttachmentMarkdownPage[] } {
    const pagesByNumber = new Map<number, DomReadItem[]>();
    const orderedItems = document.sections
        .slice()
        .sort((a, b) => a.index - b.index)
        .flatMap((section) => section.items
            .slice()
            .sort((a, b) => a.order - b.order)
            .map((item) => ({
                ...item,
                pageNumber: item.pageNumber ?? section.index + 1,
            })));

    for (const item of orderedItems) {
        const pageNumber = item.pageNumber ?? 1;
        const pageItems = pagesByNumber.get(pageNumber);
        if (pageItems) {
            pageItems.push(item);
        } else {
            pagesByNumber.set(pageNumber, [item]);
        }
    }

    // An item is stamped with the page of its first text node, so a single item
    // longer than the synthetic page interval (a long <p>/<pre> or a linearized
    // table) spans interior pages that no item is stamped to.
    const observedPageCount = Math.max(0, ...Array.from(pagesByNumber.keys()));
    const pageCount = Math.max(document.pageCount ?? observedPageCount, observedPageCount);
    const pages: AttachmentMarkdownPage[] = [];
    for (let pageNumber = 1; pageNumber <= pageCount; pageNumber++) {
        const items = pagesByNumber.get(pageNumber) ?? [];
        pages.push({
            pageNumber,
            markdown: items
                .map(domItemToMarkdown)
                .filter((text) => text.length > 0)
                .join('\n\n'),
        });
    }
    return { pageCount, pages };
}

function domItemToMarkdown(item: { kind: string; text?: string; level?: number; sentences?: Array<{ text: string }> }): string {
    const text = normalizeMarkdownText(
        item.text ?? item.sentences?.map((sentence) => sentence.text).join(' ') ?? '',
    );
    if (!text) return '';

    switch (item.kind) {
        case 'section_header': {
            const level = Math.min(Math.max(item.level ?? 2, 1), 6);
            return `${'#'.repeat(level)} ${text}`;
        }
        case 'list_item':
            return `- ${text}`;
        case 'caption':
            return `_${text}_`;
        case 'footnote':
            return `[^] ${text}`;
        default:
            return text;
    }
}

function normalizeMarkdownText(text: string): string {
    return text.replace(/\s+/g, ' ').trim();
}

/**
 * Handler for the MCP `read_note` tool.
 *
 * Exported so dev-only endpoints can exercise the same MCP adapter used by
 * external clients.
 */
export async function handleReadNote(args: any): Promise<any> {
    args = args ?? {};
    if (!args.note_id || typeof args.note_id !== 'string') {
        return mcpError('note_id is required and must be a string.');
    }

    const wsRequest: WSReadNoteRequest = {
        event: 'read_note_request',
        request_id: generateRequestId(),
        note_id: args.note_id,
        offset: args.offset,
        limit: args.limit,
    };

    const response: WSReadNoteResponse = await handleReadNoteRequest(wsRequest);

    if (!response.success) {
        return mcpError(response.error ?? 'Failed to read note');
    }

    return {
        note_id: response.note_id,
        title: response.title ?? null,
        parent_item_id: response.parent_item_id ?? null,
        parent_title: response.parent_title ?? null,
        total_lines: response.total_lines ?? null,
        lines_returned: response.lines_returned ?? null,
        has_more: response.has_more ?? false,
        next_offset: response.next_offset ?? null,
        content: response.content ?? '',
        cited_items: (response.cited_items ?? []).map((item) => ({
            item_id: `${item.library_id}-${item.zotero_key}`,
            item_type: item.item_type,
            title: item.title ?? null,
        })),
    };
}

function buildNoopTimeoutContext(): TimeoutContext {
    return {
        signal: new AbortController().signal,
        timeoutSeconds: 120,
        startTime: Date.now(),
    };
}

/**
 * Handler for the MCP `create_note` tool.
 *
 * The host MCP client owns approval UX, so this adapter validates and then
 * executes directly instead of entering Beaver's deferred-action queue.
 */
export async function handleCreateNote(args: any): Promise<any> {
    args = args ?? {};
    const title = typeof args.title === 'string' ? args.title.trim() : '';
    const content = typeof args.content === 'string' ? args.content : '';

    if (!title) {
        return mcpError('title is required and cannot be empty.');
    }
    if (!content.trim()) {
        return mcpError('content is required and cannot be empty.');
    }

    const effectiveCollection = args.parent_id ? undefined : args.collection;
    const actionData = {
        title,
        content,
        parent_item_id: args.parent_id,
        library: args.library,
        collection: effectiveCollection,
    };

    const validateRequest: WSAgentActionValidateRequest = {
        event: 'agent_action_validate',
        request_id: generateRequestId(),
        action_type: 'create_note',
        action_data: actionData,
    };

    const validation = await validateCreateNoteAction(validateRequest);
    if (!validation.valid) {
        return mcpError(validation.error ?? 'Create note validation failed');
    }

    const mergedActionData = {
        ...actionData,
        ...(validation.normalized_action_data ?? {}),
    };

    const executeRequest: WSAgentActionExecuteRequest = {
        event: 'agent_action_execute',
        request_id: generateRequestId(),
        action_type: 'create_note',
        action_data: mergedActionData,
    };

    const response: WSAgentActionExecuteResponse = await executeCreateNoteAction(
        executeRequest,
        buildNoopTimeoutContext(),
    );

    if (!response.success) {
        return mcpError(response.error ?? 'Failed to create note');
    }

    const result = response.result_data ?? {};
    const libraryId = result.library_id;
    const noteKey = result.zotero_key;
    const citedItemsData = result.cited_items_data ?? {};

    return {
        note_id: libraryId != null && noteKey ? `${libraryId}-${noteKey}` : null,
        parent_item_id: libraryId != null && result.parent_key ? `${libraryId}-${result.parent_key}` : null,
        related_item_id: libraryId != null && result.related_item_key ? `${libraryId}-${result.related_item_key}` : null,
        collection_key: result.collection_key ?? null,
        note_content: result.note_content ?? null,
        warning: result.warning ?? null,
        citation_issues: {
            invalid_keys: citedItemsData.invalid_keys ?? [],
            errors: citedItemsData.errors ?? [],
        },
    };
}

async function handleGetItemDetails(args: any): Promise<any> {
    const itemIds: string[] = args.item_ids;
    if (!itemIds || itemIds.length === 0) {
        return mcpError('item_ids must be a non-empty array.');
    }
    if (itemIds.length > 25) {
        return mcpError(`Too many items requested (${itemIds.length}). Maximum is 25.`);
    }

    const wsRequest: WSGetMetadataRequest = {
        event: 'get_metadata_request',
        request_id: generateRequestId(),
        item_ids: itemIds,
        include_attachments: args.include_attachments ?? false,
        include_notes: args.include_notes ?? false,
    };

    const response: WSGetMetadataResponse = await handleGetMetadataRequest(wsRequest);

    if (response.error) {
        return mcpError(`Failed to get item details: ${response.error}`);
    }

    // Enrich items with zotero_uri, citation keys, and transform attachments
    const items = await Promise.all(response.items.map(async (item) => {
        const parsed = parseItemId(item.item_id);

        // Add zotero://select URI
        if (parsed) {
            const zoteroUri = getZoteroSelectURI(parsed.libraryId, parsed.key);
            if (zoteroUri) item.zotero_uri = zoteroUri;
        }

        // Add citation_key (BetterBibTeX-aware) if not already present
        if (!item.citationKey && parsed) {
            try {
                const zoteroItem = await Zotero.Items.getByLibraryAndKeyAsync(parsed.libraryId, parsed.key);
                if (zoteroItem) {
                    const citationKey = await getCitationKeyFromItem(zoteroItem);
                    if (citationKey) item.citationKey = citationKey;
                }
            } catch { /* best-effort */ }
        }

        if (item.attachments && Array.isArray(item.attachments)) {
            item.attachments = item.attachments.map((a: any) => {
                return {
                    attachment_id: getMcpAttachmentId(a),
                    filename: a.filename || null,
                    content_type: a.content_type ?? a.contentType ?? null,
                    content_kind: a.content_kind ?? null,
                    page_count: a.page_count ?? null,
                    annotations_count: a.annotations_count,
                    status: getMcpAttachmentStatus(a),
                };
            });
        }
        if (item.notes && Array.isArray(item.notes)) {
            item.notes = item.notes.map((n: any) => ({
                item_id: n.item_id,
                title: n.title || null,
                parent_item_id: n.parent_item_id ?? null,
                parent_title: n.parent_title ?? null,
                date_modified: n.date_modified ?? null,
            }));
        }
        // Remove internal fields not useful for MCP consumers
        delete item.item_metadata_hash;
        delete item.zotero_version;
        delete item.zotero_synced;
        delete item.item_json;
        return item;
    }));

    return {
        items,
        not_found: response.not_found,
    };
}

async function handleListCollections(args: any): Promise<any> {
    const limit = Math.min(Math.max(1, args.limit ?? 50), 100);
    const offset = Math.max(0, args.offset ?? 0);

    // Parse library parameter — can be a name or ID string
    let libraryId: number | string | null = null;
    if (args.library != null) {
        const parsed = parseInt(args.library, 10);
        libraryId = isNaN(parsed) ? args.library : parsed;
    }

    const wsRequest: WSListCollectionsRequest = {
        event: 'list_collections_request',
        request_id: generateRequestId(),
        library_id: libraryId,
        parent_collection_key: args.parent_collection ?? null,
        include_item_counts: args.include_item_counts ?? true,
        limit,
        offset,
    };

    const response: WSListCollectionsResponse = await handleListCollectionsRequest(wsRequest);

    if (response.error) {
        return mcpError(`Failed to list collections: ${response.error}`);
    }

    const hasMore = offset + limit < response.total_count;

    return {
        total_count: response.total_count,
        has_more: hasMore,
        next_offset: hasMore ? offset + limit : null,
        // library_id/library_name carry the library scope each collection row needs
        // (used when building the hydrated collection-list view for rendering).
        library_id: response.library_id,
        library_name: response.library_name,
        collections: response.collections.map((c) => ({
            collection_key: c.collection_key,
            name: c.name,
            item_count: c.item_count,
            subcollection_count: c.subcollection_count,
        })),
    };
}

async function handleListTags(args: any): Promise<any> {
    const limit = Math.min(Math.max(1, args.limit ?? 50), 100);
    const offset = Math.max(0, args.offset ?? 0);

    let libraryId: number | string | null = null;
    if (args.library != null) {
        const parsed = parseInt(args.library, 10);
        libraryId = isNaN(parsed) ? args.library : parsed;
    }

    const wsRequest: WSListTagsRequest = {
        event: 'list_tags_request',
        request_id: generateRequestId(),
        library_id: libraryId,
        collection_key: args.collection ?? null,
        min_item_count: args.min_item_count ?? 1,
        limit,
        offset,
    };

    const response: WSListTagsResponse = await handleListTagsRequest(wsRequest);

    if (response.error) {
        return mcpError(`Failed to list tags: ${response.error}`);
    }

    const hasMore = offset + limit < response.total_count;

    return {
        total_count: response.total_count,
        has_more: hasMore,
        next_offset: hasMore ? offset + limit : null,
        tags: response.tags.map((t) => {
            const tag: any = {
                name: t.name,
                item_count: t.item_count,
                attachment_count: t.attachment_count ?? 0,
                note_count: t.note_count ?? 0,
                annotation_count: t.annotation_count ?? 0,
            };
            if (t.color) tag.color = t.color;
            return tag;
        }),
    };
}

async function handleListItems(args: any): Promise<any> {
    const limit = Math.min(Math.max(1, args.limit ?? 20), 100);
    const offset = Math.max(0, args.offset ?? 0);

    let libraryId: number | string | null = null;
    if (args.library != null) {
        const parsed = parseInt(args.library, 10);
        libraryId = isNaN(parsed) ? args.library : parsed;
    }

    const validSortFields = ['dateAdded', 'dateModified', 'title', 'creator', 'year'];
    const sortBy = validSortFields.includes(args.sort_by) ? args.sort_by : 'dateModified';
    const sortOrder = args.sort_order === 'asc' ? 'asc' : 'desc';

    const validCategories: ZoteroItemCategory[] = ['regular', 'note', 'attachment', 'all'];
    const itemCategory: ZoteroItemCategory = validCategories.includes(args.item_category)
        ? args.item_category
        : 'regular';

    const wsRequest: WSListItemsRequest = {
        event: 'list_items_request',
        request_id: generateRequestId(),
        library_id: libraryId,
        collection_key: args.collection ?? null,
        tag: args.tag ?? null,
        item_category: itemCategory,
        recursive: args.recursive ?? true,
        sort_by: sortBy,
        sort_order: sortOrder,
        limit,
        offset,
    };

    const response: WSListItemsResponse = await handleListItemsRequest(wsRequest);

    if (response.error) {
        return mcpError(`Failed to list items: ${response.error}`);
    }

    const hasMore = offset + limit < response.total_count;

    return {
        total_count: response.total_count,
        has_more: hasMore,
        next_offset: hasMore ? offset + limit : null,
        // With item_category other than 'regular', results can be notes or attachments,
        // so format each item according to its result_type rather than assuming regular.
        items: response.items.map((item) => {
            const rowItemId = item.result_type === 'attachment'
                ? (item.attachment_id ?? (item as any).item_id)
                : item.item_id;
            const parsed = parseItemId(rowItemId);
            const zoteroUri = parsed ? getZoteroSelectURI(parsed.libraryId, parsed.key) : null;
            const uriField = zoteroUri ? { zotero_uri: zoteroUri } : {};

            if (item.result_type === 'note') {
                const note = item as NoteResultItem;
                return {
                    item_id: note.item_id,
                    item_type: 'note',
                    title: note.title ?? null,
                    parent_item_id: note.parent_item_id ?? null,
                    parent_title: note.parent_title ?? null,
                    date_modified: note.date_modified ?? null,
                    ...uriField,
                };
            }

            if (item.result_type === 'attachment') {
                const attachment = item as AttachmentRowResult;
                const attachmentId = getMcpAttachmentId(attachment);
                return {
                    attachment_id: attachmentId,
                    item_id: attachmentId,
                    item_type: 'attachment',
                    title: attachment.title ?? null,
                    filename: attachment.filename ?? null,
                    content_kind: attachment.content_kind,
                    content_type: (attachment as any).content_type ?? null,
                    status: getMcpAttachmentStatus(attachment),
                    status_reason: attachment.status_reason ?? null,
                    parent_item_id: attachment.parent_item_id ?? null,
                    parent_title: attachment.parent_title ?? null,
                    annotations_count: attachment.annotations_count ?? null,
                    date_modified: attachment.date_modified ?? null,
                    ...uriField,
                };
            }

            const regular = item as RegularListResultItem;
            return {
                item_id: regular.item_id,
                item_type: regular.item_type,
                title: regular.title ?? null,
                authors: regular.creators ?? null,
                year: regular.year ?? null,
                date_added: regular.date_added ?? null,
                date_modified: regular.date_modified ?? null,
                ...uriField,
            };
        }),
    };
}

// =============================================================================
// Hook
// =============================================================================

export function useMcpServer() {
    const enabled = useAtomValue(mcpServerEnabledAtom);
    const createNoteToolEnabled = useAtomValue(mcpCreateNoteToolEnabledAtom);

    useEffect(() => {
        if (!enabled) {
            return;
        }

        logger('useMcpServer: MCP server enabled, registering endpoint', 3);

        // Write the stdio bridge script for MCP clients like Claude Desktop
        ensureMcpBridgeScript().catch((err) => {
            logger(`useMcpServer: Failed to write MCP bridge script: ${err?.message}`, 1);
        });

        const service = new MCPService();
        service.setAuthCheck(() => store.get(isAuthenticatedAtom));

        const tools: McpToolRegistration[] = [
            { def: SEARCH_BY_TOPIC_TOOL, handler: handleSearchByTopic },
            { def: SEARCH_BY_METADATA_TOOL, handler: handleSearchByMetadata },
            { def: READ_ATTACHMENT_TOOL, handler: handleReadAttachment },
            { def: READ_NOTE_TOOL, handler: handleReadNote },
            { def: GET_ITEM_DETAILS_TOOL, handler: handleGetItemDetails },
            { def: LIST_COLLECTIONS_TOOL, handler: handleListCollections },
            { def: LIST_TAGS_TOOL, handler: handleListTags },
            { def: LIST_ITEMS_TOOL, handler: handleListItems },
        ];
        if (createNoteToolEnabled) {
            tools.push({ def: CREATE_NOTE_TOOL, handler: handleCreateNote });
        }

        for (const { def, handler } of tools) {
            service.registerTool(def.name, def, handler);
        }

        const registered = service.register();

        return () => {
            if (registered) {
                logger('useMcpServer: Cleaning up MCP endpoint', 3);
                service.unregister();
            }
        };
    }, [enabled, createNoteToolEnabled]);
}
