/**
 * Builds self-contained HTML reports that render inside Zotero's snapshot reader.
 *
 * The reader loads snapshots in a sandboxed iframe under a fixed CSP:
 *
 *   default-src zotero:; img-src zotero: data: blob:;
 *   style-src zotero: data: 'unsafe-inline'; font-src zotero: resource: data: blob:;
 *   script-src 'unsafe-eval'; child-src 'none'; form-action 'none'
 *
 * Consequences this module is built around:
 *   - Author JavaScript never runs. Anything dynamic must be precomputed here.
 *   - No network of any kind. Images must be inline SVG or data: URIs.
 *   - Inline <style> and style attributes are allowed, so full CSS layout works.
 *
 * The reader also themes snapshots automatically, and how it does that depends on
 * the top-level CSS rule count (see CSS_RULE_BUDGET). Staying under the budget keeps
 * documents on the Dark Reader path, which remaps colors while preserving contrast
 * relationships. The stylesheet below is written to survive either path.
 *
 * This module is deliberately free of Zotero APIs: callers pass prebuilt link URIs.
 */

/**
 * The reader counts top-level rules per author stylesheet and switches to a static
 * theme above 500. The static theme forces `background-color: transparent !important`
 * and a single text color onto every element, which flattens a designed palette.
 * Reports stay well under the threshold so the nicer dynamic path is always used.
 */
export const CSS_RULE_BUDGET = 500;

export interface ReportCitation {
    /** Display label, e.g. "Anderson & Lee (2019)". */
    label: string;
    /** Full reference line rendered under the label. */
    reference?: string;
    /** zotero://select URI that reveals the item in the library. */
    selectUri?: string | null;
    /** zotero://open URI for a file attachment, when one exists. */
    openUri?: string | null;
    /** Optional locator shown next to the open link, e.g. "p. 14". */
    locator?: string | null;
}

export type ReportBlock =
    | { type: 'paragraph'; text: string }
    | { type: 'list'; ordered?: boolean; items: string[] }
    | { type: 'table'; columns: string[]; rows: string[][] }
    | { type: 'bar_chart'; caption?: string; series: { label: string; value: number }[]; unit?: string }
    | { type: 'callout'; variant: 'note' | 'warning'; title: string; text: string }
    | { type: 'citations'; entries: ReportCitation[] };

export interface ReportSection {
    heading: string;
    blocks: ReportBlock[];
}

export interface ReportSpec {
    title: string;
    subtitle?: string;
    /** Free-text provenance line, e.g. "Generated by Beaver on 3 August 2026". */
    provenance?: string;
    sections: ReportSection[];
    footerNote?: string;
}

export interface BuiltReport {
    html: string;
    /** Top-level rule count of the emitted stylesheet, for budget assertions. */
    cssRuleCount: number;
}

const ESCAPE_MAP: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
};

/** Escapes text for HTML body/attribute context. All model-authored text goes through this. */
export function escapeHtml(value: string): string {
    return String(value).replace(/[&<>"']/g, (ch) => ESCAPE_MAP[ch]);
}

/**
 * Only `zotero:` links are emitted. Anything else is rendered as plain text so a
 * generated report can never become a clickable path to an arbitrary destination.
 */
function safeUri(uri: string | null | undefined): string | null {
    if (!uri) return null;
    return /^zotero:\/\//i.test(uri) ? uri : null;
}

/**
 * Palette and layout.
 *
 * Two rules keep this readable in both of the reader's theming modes:
 *   - Meaning is never carried by `background-color` alone. The static theme drops
 *     every background with `!important`, so state is signalled by border and text.
 *   - Semantic text colors are written at two-class specificity (e.g.
 *     `.rp-tag.rp-tag--warn`). The static theme's `body.force-static-theme *` rule
 *     sits at (0,1,1) and would otherwise flatten single-class colors.
 */
const REPORT_CSS = `
:root {
  --rp-fg: #16181d;
  --rp-muted: #5b6472;
  --rp-line: #dfe3e8;
  --rp-accent: #2f5bd7;
  --rp-warn: #a04a00;
}
body { margin: 0; padding: 40px 24px 72px; background: #fff; color: var(--rp-fg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  font-size: 15px; line-height: 1.6; }
.rp { max-width: 780px; margin: 0 auto; }
.rp-title { font-size: 28px; line-height: 1.25; letter-spacing: -0.02em; margin: 0 0 6px; }
.rp-subtitle { font-size: 16px; margin: 0 0 10px; }
.rp-provenance { font-size: 13px; margin: 0 0 32px; padding-bottom: 18px;
  border-bottom: 1px solid var(--rp-line); }
.rp h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.09em;
  font-weight: 650; margin: 36px 0 12px; }
.rp p { margin: 0 0 12px; }
.rp ul, .rp ol { margin: 0 0 12px; padding-left: 22px; }
.rp li { margin-bottom: 5px; }
.rp-table-wrap { overflow-x: auto; margin: 0 0 14px; }
.rp table { border-collapse: collapse; width: 100%; font-size: 14px; }
.rp th, .rp td { text-align: left; padding: 9px 12px; border-bottom: 1px solid var(--rp-line);
  vertical-align: top; }
.rp th { font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 650; }
.rp-figure { margin: 0 0 16px; padding: 16px; border: 1px solid var(--rp-line); border-radius: 10px; }
.rp-figure svg { display: block; width: 100%; height: auto; }
.rp-caption { font-size: 13px; margin: 10px 0 0; }
.rp-callout { margin: 0 0 14px; padding: 14px 16px; border: 1px solid var(--rp-line);
  border-left-width: 4px; border-radius: 8px; }
.rp-callout-title { font-weight: 650; margin: 0 0 4px; }
.rp-callout p { margin: 0; }
.rp-cites { list-style: none; margin: 0; padding: 0; }
.rp-cite { padding: 12px 0; border-bottom: 1px solid var(--rp-line); }
.rp-cite-label { font-weight: 600; }
.rp-cite-ref { font-size: 14px; margin: 2px 0 6px; }
.rp-cite-links { font-size: 13px; }
.rp-cite-links a { color: var(--rp-accent); text-decoration: none;
  border-bottom: 1px solid var(--rp-line); }
.rp-cite-links .rp-sep { padding: 0 8px; }
.rp-footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--rp-line);
  font-size: 13px; }
.rp-empty { font-style: italic; }
.rp .rp-muted { color: var(--rp-muted); }
.rp .rp-accent { color: var(--rp-accent); }
.rp-callout.rp-callout--warn { border-left-color: var(--rp-warn); }
.rp-callout.rp-callout--note { border-left-color: var(--rp-accent); }
.rp-callout.rp-callout--warn .rp-callout-title { color: var(--rp-warn); }
.rp-callout.rp-callout--note .rp-callout-title { color: var(--rp-accent); }
`.trim();

/** Counts top-level rules the way the reader does (nested at-rule bodies are not counted). */
export function countTopLevelCssRules(css: string): number {
    let depth = 0;
    let count = 0;
    for (const ch of css) {
        if (ch === '{') {
            if (depth === 0) count++;
            depth++;
        } else if (ch === '}') {
            depth = Math.max(0, depth - 1);
        }
    }
    return count;
}

const CHART_FILLS = ['#2f5bd7', '#6d4bc4', '#0e7c86', '#a04a00', '#3f6212', '#9d174d'];

/**
 * Renders a bar chart as inline SVG with geometry computed here, since no script runs.
 *
 * Bars use explicit fills rather than `currentColor`: the reader's static theme sets
 * `color` on every element, which would otherwise repaint the whole chart one color.
 */
function renderBarChart(series: { label: string; value: number }[], unit?: string): string {
    if (!series.length) return '<p class="rp-empty rp-muted">No data.</p>';

    const width = 680;
    const rowHeight = 34;
    const gap = 10;
    const labelWidth = 190;
    // Values are right-aligned to the viewBox edge, so this only has to fit the
    // widest number. Units live in the caption rather than on every row, which
    // would otherwise overflow the viewBox and be clipped.
    const valueWidth = 52;
    const trackWidth = width - labelWidth - valueWidth;
    const height = series.length * (rowHeight + gap);
    const max = Math.max(...series.map((s) => (Number.isFinite(s.value) ? Math.abs(s.value) : 0)), 1);

    const bars = series.map((point, i) => {
        const value = Number.isFinite(point.value) ? point.value : 0;
        const y = i * (rowHeight + gap);
        const barWidth = Math.max(2, Math.round((Math.abs(value) / max) * trackWidth));
        const fill = CHART_FILLS[i % CHART_FILLS.length];
        return [
            `<text x="0" y="${y + rowHeight / 2 + 4}" font-size="13" fill="#5b6472">${escapeHtml(point.label)}</text>`,
            `<rect x="${labelWidth}" y="${y + 4}" width="${trackWidth}" height="${rowHeight - 8}" rx="4" fill="#eef1f5"></rect>`,
            `<rect x="${labelWidth}" y="${y + 4}" width="${barWidth}" height="${rowHeight - 8}" rx="4" fill="${fill}"></rect>`,
            `<text x="${width}" y="${y + rowHeight / 2 + 4}" font-size="13" text-anchor="end" fill="#16181d">${escapeHtml(String(value))}</text>`,
        ].join('');
    });

    const summary = series.map((s) => `${s.label}: ${s.value}${unit ? ` ${unit}` : ''}`).join('; ');
    return (
        `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeHtml(summary)}" ` +
        `xmlns="http://www.w3.org/2000/svg">${bars.join('')}</svg>`
    );
}

function renderCitation(entry: ReportCitation): string {
    const selectUri = safeUri(entry.selectUri);
    const openUri = safeUri(entry.openUri);

    const links: string[] = [];
    if (selectUri) {
        links.push(`<a href="${escapeHtml(selectUri)}">Show in library</a>`);
    }
    if (openUri) {
        const locator = entry.locator ? ` (${escapeHtml(entry.locator)})` : '';
        links.push(`<a href="${escapeHtml(openUri)}">Open attachment</a>${locator}`);
    }

    return [
        '<li class="rp-cite">',
        `<div class="rp-cite-label">${escapeHtml(entry.label)}</div>`,
        entry.reference ? `<div class="rp-cite-ref rp-muted">${escapeHtml(entry.reference)}</div>` : '',
        links.length ? `<div class="rp-cite-links">${links.join('<span class="rp-sep rp-muted">·</span>')}</div>` : '',
        '</li>',
    ].join('');
}

function renderBlock(block: ReportBlock): string {
    switch (block.type) {
        case 'paragraph':
            return `<p>${escapeHtml(block.text)}</p>`;

        case 'list': {
            const tag = block.ordered ? 'ol' : 'ul';
            const items = block.items.map((item) => `<li>${escapeHtml(item)}</li>`).join('');
            return `<${tag}>${items}</${tag}>`;
        }

        case 'table': {
            const head = block.columns.map((c) => `<th>${escapeHtml(c)}</th>`).join('');
            const body = block.rows
                .map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`)
                .join('');
            return `<div class="rp-table-wrap"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;
        }

        case 'bar_chart': {
            const captionText = [block.caption, block.unit ? `Values in ${block.unit}.` : '']
                .filter(Boolean)
                .join(' ');
            const caption = captionText
                ? `<p class="rp-caption rp-muted">${escapeHtml(captionText)}</p>`
                : '';
            return `<figure class="rp-figure">${renderBarChart(block.series, block.unit)}${caption}</figure>`;
        }

        case 'callout':
            return [
                `<div class="rp-callout rp-callout--${block.variant === 'warning' ? 'warn' : 'note'}">`,
                `<p class="rp-callout-title">${escapeHtml(block.title)}</p>`,
                `<p>${escapeHtml(block.text)}</p>`,
                '</div>',
            ].join('');

        case 'citations':
            if (!block.entries.length) {
                return '<p class="rp-empty rp-muted">No sources cited.</p>';
            }
            return `<ul class="rp-cites">${block.entries.map(renderCitation).join('')}</ul>`;

        default:
            return '';
    }
}

/**
 * Builds the complete document. The output contains no <script>, no external
 * references, and no resources beyond what is inlined here.
 */
export function buildReportHtml(spec: ReportSpec): BuiltReport {
    const sections = spec.sections
        .map((section) => {
            const blocks = section.blocks.map(renderBlock).join('\n');
            return `<section><h2 class="rp-muted">${escapeHtml(section.heading)}</h2>\n${blocks}</section>`;
        })
        .join('\n');

    const html = [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="utf-8">',
        `<title>${escapeHtml(spec.title)}</title>`,
        `<style>\n${REPORT_CSS}\n</style>`,
        '</head>',
        '<body>',
        '<article class="rp">',
        `<h1 class="rp-title">${escapeHtml(spec.title)}</h1>`,
        spec.subtitle ? `<p class="rp-subtitle rp-muted">${escapeHtml(spec.subtitle)}</p>` : '',
        spec.provenance ? `<p class="rp-provenance rp-muted">${escapeHtml(spec.provenance)}</p>` : '',
        sections,
        spec.footerNote ? `<footer class="rp-footer rp-muted">${escapeHtml(spec.footerNote)}</footer>` : '',
        '</article>',
        '</body>',
        '</html>',
        '',
    ]
        .filter(Boolean)
        .join('\n');

    return { html, cssRuleCount: countTopLevelCssRules(REPORT_CSS) };
}
